"""
agent/html_report.py
─────────────────────
Converts a markdown pentest report into a styled HTML report
with a severity dashboard and color-coded findings.
"""

import re
from pathlib import Path
from datetime import datetime


SEVERITY_COLORS = {
    "CRITICAL": ("#dc2626", "#fee2e2"),
    "HIGH":     ("#ea580c", "#ffedd5"),
    "MEDIUM":   ("#ca8a04", "#fef9c3"),
    "LOW":      ("#16a34a", "#dcfce7"),
}

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AutoRedTeam Report — {target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
  .header {{ background: linear-gradient(135deg, #1e293b, #0f172a);
             border-bottom: 1px solid #334155; padding: 2rem; }}
  .header h1 {{ font-size: 1.8rem; color: #38bdf8; }}
  .header .meta {{ color: #94a3b8; font-size: 0.9rem; margin-top: 0.5rem; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem; }}
  .dashboard {{ display: grid; grid-template-columns: repeat(4, 1fr);
                gap: 1rem; margin: 2rem 0; }}
  .card {{ background: #1e293b; border-radius: 8px; padding: 1.5rem;
           text-align: center; border-top: 3px solid; }}
  .card.critical {{ border-color: #dc2626; }}
  .card.high     {{ border-color: #ea580c; }}
  .card.medium   {{ border-color: #ca8a04; }}
  .card.low      {{ border-color: #16a34a; }}
  .card .count {{ font-size: 3rem; font-weight: bold; }}
  .card.critical .count {{ color: #dc2626; }}
  .card.high     .count {{ color: #ea580c; }}
  .card.medium   .count {{ color: #ca8a04; }}
  .card.low      .count {{ color: #16a34a; }}
  .card .label {{ color: #94a3b8; font-size: 0.85rem; text-transform: uppercase;
                  letter-spacing: 1px; margin-top: 0.3rem; }}
  .section {{ margin: 2rem 0; }}
  .section h2 {{ font-size: 1.3rem; color: #38bdf8; border-bottom: 1px solid #334155;
                 padding-bottom: 0.5rem; margin-bottom: 1rem; }}
  .finding {{ background: #1e293b; border-radius: 8px; margin: 1rem 0;
              border-left: 4px solid; overflow: hidden; }}
  .finding.critical {{ border-color: #dc2626; }}
  .finding.high     {{ border-color: #ea580c; }}
  .finding.medium   {{ border-color: #ca8a04; }}
  .finding.low      {{ border-color: #16a34a; }}
  .finding-header {{ padding: 1rem 1.5rem; display: flex; align-items: center; gap: 1rem; }}
  .badge {{ padding: 0.2rem 0.7rem; border-radius: 4px; font-size: 0.75rem;
            font-weight: bold; text-transform: uppercase; }}
  .badge.critical {{ background: #dc2626; color: white; }}
  .badge.high     {{ background: #ea580c; color: white; }}
  .badge.medium   {{ background: #ca8a04; color: white; }}
  .badge.low      {{ background: #16a34a; color: white; }}
  .finding-title {{ font-weight: 600; font-size: 1rem; }}
  .finding-body {{ padding: 0 1.5rem 1.5rem; color: #cbd5e1; }}
  .finding-body strong {{ color: #e2e8f0; }}
  .finding-body p {{ margin: 0.4rem 0; font-size: 0.9rem; }}
  pre {{ background: #0f172a; padding: 1rem; border-radius: 6px; overflow-x: auto;
         font-size: 0.82rem; color: #a3e635; margin: 0.5rem 0; }}
  .exec-summary {{ background: #1e293b; border-radius: 8px; padding: 1.5rem;
                   color: #cbd5e1; font-size: 0.95rem; }}
  .remediation {{ background: #1e293b; border-radius: 8px; padding: 1.5rem; margin: 0.8rem 0; }}
  .remediation h3 {{ color: #38bdf8; margin-bottom: 0.8rem; font-size: 0.95rem; }}
  .footer {{ text-align: center; color: #475569; font-size: 0.8rem; padding: 2rem;
             border-top: 1px solid #1e293b; margin-top: 3rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>AutoRedTeam Pentest Report</h1>
  <div class="meta">
    Target: <strong>{target}</strong> &nbsp;|&nbsp;
    Date: <strong>{date}</strong> &nbsp;|&nbsp;
    Assessed By: <strong>AutoRedTeam AI Agent</strong>
  </div>
</div>
<div class="container">
  <div class="dashboard">
    <div class="card critical"><div class="count">{critical}</div><div class="label">Critical</div></div>
    <div class="card high">   <div class="count">{high}</div>   <div class="label">High</div></div>
    <div class="card medium"> <div class="count">{medium}</div> <div class="label">Medium</div></div>
    <div class="card low">    <div class="count">{low}</div>    <div class="label">Low</div></div>
  </div>

  <div class="section">
    <h2>Executive Summary</h2>
    <div class="exec-summary">{summary}</div>
  </div>

  <div class="section">
    <h2>Findings</h2>
    {findings_html}
  </div>

  {remediation_html}

</div>
<div class="footer">
  Generated by AutoRedTeam AI Agent &nbsp;|&nbsp; {date}
</div>
</body>
</html>
"""

FINDING_TEMPLATE = """\
<div class="finding {sev_lower}">
  <div class="finding-header">
    <span class="badge {sev_lower}">{severity}</span>
    <span class="finding-title">{title}</span>
  </div>
  <div class="finding-body">
    {body_html}
  </div>
</div>
"""


def _extract_section(text: str, heading: str, next_heading: str = None) -> str:
    start = text.find(f"## {heading}")
    if start == -1:
        return ""
    start = text.find("\n", start) + 1
    if next_heading:
        end = text.find(f"## {next_heading}", start)
        return text[start:end].strip() if end != -1 else text[start:].strip()
    return text[start:].strip()


def _parse_findings(findings_text: str) -> list[dict]:
    findings = []
    blocks = re.split(r"\n### ", findings_text)
    for block in blocks:
        if not block.strip():
            continue
        lines = block.strip().split("\n")
        header = lines[0].strip()
        sev_match = re.match(r"\[(CRITICAL|HIGH|MEDIUM|LOW)\]\s*(.*)", header)
        if not sev_match:
            continue
        severity, title = sev_match.groups()
        body = "\n".join(lines[1:]).strip()
        findings.append({"severity": severity, "title": title.strip(), "body": body})
    return findings


def _body_to_html(body: str) -> str:
    lines = body.split("\n")
    html_lines = []
    in_code = False
    for line in lines:
        if line.strip().startswith("```"):
            if in_code:
                html_lines.append("</pre>")
                in_code = False
            else:
                html_lines.append("<pre>")
                in_code = True
        elif in_code:
            html_lines.append(line.replace("<", "&lt;").replace(">", "&gt;"))
        elif line.startswith("- **") or line.startswith("* **"):
            content = line.lstrip("- *")
            content = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", content)
            html_lines.append(f"<p>{content}</p>")
        elif line.strip():
            content = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", line)
            html_lines.append(f"<p>{content}</p>")
    if in_code:
        html_lines.append("</pre>")
    return "\n".join(html_lines)


def _remediation_to_html(remediation_text: str) -> str:
    if not remediation_text:
        return ""
    blocks = re.split(r"\n### Fix:", remediation_text)
    html = '<div class="section"><h2>Remediation Playbook</h2>'
    for block in blocks[1:]:
        lines = block.strip().split("\n")
        title = lines[0].strip()
        body = _body_to_html("\n".join(lines[1:]))
        html += f'<div class="remediation"><h3>Fix: {title}</h3>{body}</div>'
    html += "</div>"
    return html


def generate_html_report(markdown_report: str, target: str) -> str:
    summary    = _extract_section(markdown_report, "Executive Summary", "Findings")
    findings_t = _extract_section(markdown_report, "Findings", "Risk Summary")
    remediation_t = _extract_section(markdown_report, "Remediation Playbook")

    findings = _parse_findings(findings_t)

    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    findings_html = ""
    for f in findings:
        sev = f["severity"]
        counts[sev] = counts.get(sev, 0) + 1
        findings_html += FINDING_TEMPLATE.format(
            sev_lower=sev.lower(),
            severity=sev,
            title=f["title"],
            body_html=_body_to_html(f["body"]),
        )

    return HTML_TEMPLATE.format(
        target=target,
        date=datetime.now().strftime("%Y-%m-%d"),
        critical=counts["CRITICAL"],
        high=counts["HIGH"],
        medium=counts["MEDIUM"],
        low=counts["LOW"],
        summary=summary.replace("\n", "<br>"),
        findings_html=findings_html,
        remediation_html=_remediation_to_html(remediation_t),
    )


def save_html_report(markdown_report: str, target: str, md_path: Path) -> Path:
    html = generate_html_report(markdown_report, target)
    html_path = md_path.with_suffix(".html")
    html_path.write_text(html)
    return html_path
