"""
Notes Agent — runs after every alert regardless of verdict.

Writes one Markdown case file per alert into cases/ (Obsidian/Logseq-friendly:
plain markdown, YAML frontmatter, no server). The structured facts are templated
deterministically; a short narrative summary is generated by Claude (Haiku).
"""

from __future__ import annotations

import json

from common import CaseContext, claude_complete, extract_json, NOTES_MODEL, CASES_DIR


def _summary(case: CaseContext) -> str:
    try:
        return claude_complete(
            model=NOTES_MODEL,
            system="Write a 2-3 sentence SOC case summary from the facts. Plain prose, no preamble.",
            prompt=json.dumps({"alert": case.rule_description, "triage": case.triage,
                               "response": (case.response or {}).get("proposed_actions")}),
            max_tokens=200, temperature=0.3)
    except Exception as exc:
        return f"_(summary unavailable: {exc})_"


def write_note(case: CaseContext) -> CaseContext:
    CASES_DIR.mkdir(exist_ok=True)
    t = case.triage or {}
    r = case.response or {}
    path = CASES_DIR / f"{case.created_at[:10]}_{case.case_id}.md"

    lines = [
        "---",
        f"case_id: {case.case_id}",
        f"created: {case.created_at}",
        f"techniques: [{', '.join(case.techniques)}]",
        f"verdict: {t.get('verdict', 'n/a')}",
        f"confidence: {t.get('confidence', 'n/a')}",
        f"rule_id: {case.rule_id}",
        "---",
        "",
        f"# Case {case.case_id} — {t.get('verdict', 'unknown').upper()}",
        "",
        f"**Alert:** {case.rule_description}",
        f"**Host:** {case.agent_name}  |  **Rule:** {case.rule_id} (level {case.rule_level})",
        "",
        "## Summary",
        _summary(case),
        "",
        "## Triage",
        f"- **Verdict:** {t.get('verdict')} (confidence {t.get('confidence')}, threshold {t.get('threshold')})",
        f"- **Rationale:** {t.get('rationale', '')}",
        "",
        "### Key findings",
    ]
    for k, v in (t.get("key_findings") or {}).items():
        lines.append(f"- **{k}:** {v}")

    lines += ["", "## Investigation steps (tool calls)"]
    for step in case.enrichment.get("tool_trace", []):
        lines.append(f"- `{step['tool']}({json.dumps(step['input'])})` → "
                     f"{json.dumps(step['output'])[:160]}")

    lines += ["", "## Response"]
    if r.get("items"):
        if r.get("evidence"):
            ev = r["evidence"]
            lines.append(f"- **Evidence preserved (before remediation):** "
                         f"{ev.get('would_collect') or ev.get('collected')} → {ev.get('dest')}")
        lines.append(f"- **Dry run:** {r.get('dry_run')}")
        lines.append("- **Per-action decisions:**")
        for it in r["items"]:
            ap = it.get("approved")
            status = "APPROVED" if ap else ("REJECTED" if ap is False else "—")
            lines.append(f"  - **{it['action']}** on `{it.get('target_desc')}` — "
                         f"{status} ({it.get('approver', '')})")
            if it.get("rationale"):
                lines.append(f"    - Why: {it['rationale']}")
            lines.append(f"    - Result: {json.dumps(it.get('result'))[:180]}")
    else:
        lines.append(f"- {r.get('note', 'no response')}")

    path.write_text("\n".join(lines), encoding="utf-8")
    case.note_path = str(path)
    return case
